### ISSUE TITLE
Add `arXiv`/`Alternative` and `Video` link options to Thesis parsing

### ISSUE THREAD

**Issue by amkrajewski** [PhasesResearchLab/PublicationsList#3]

**Comment by amkrajewski** [comment]
I envision it to be similar to how we have articles set up. 
- arXiv is a nice place to put dissertations that may be updated in the future or otherwise fixed.
- Pretty much all defenses are recorded since COVID and provide a high-density summary of research. They should be prominently displayed if the author wishes so.

**Comment by ricardonpa** [comment]
Implemented on 25c95072993c5f3098548c51dddaf5bf6be2fc7b
